""" Converts a basic TinyBasic program (bas) to rust code (rs) """
from collections import namedtuple
import bastors.parse as parse

# Represent a line of Rust code at an indentation level
Line = namedtuple("Line", ["indent", "code"])


def format_condition(conditions):
    """
    Turns a list of the namedtuple basic condition to a Rust condition.
        Examples:
            a <> b becomes a != b
    The function will also add && or || in case of an array of condtions.
    """
    code = ""
    for cond in conditions:
        if cond.type == parse.ConditionEnum.AND:
            code += " && "
        elif cond.type == parse.ConditionEnum.OR:
            code += " || "

        if cond.operator == "<>":
            relop = "!="
        elif cond.operator == "=":
            relop = "=="
        else:
            relop = cond.operator

        code += "(%s %s %s)" % (cond.left, relop, cond.right)

    return code


class Visitor:
    """ Basis for implementing a visitor pattern to visit all nodes of the
        structure returned from the Parse module.

        Need to implement visit_Program, visit_If, visit_Print, ...
        """

    def visit(self, node):
        """ This method will find the __name__ of the node passed to it and
            call the visit method for that node. If node is a Let namedtuple
            then visit_Let() will be called. """
        method = "visit_" + type(node).__name__
        visitor = getattr(self, method, self.generic)
        return visitor(node)

    def generic(self, node):  # pylint: disable=R0201
        """ Called when no visit method found for node. """
        raise Exception("no visit method defined for %s" % type(node).__name__)


# pylint: disable=C0103
class Rustify(Visitor):
    """ This class visit all nodes of the statement tree generated by
        the Parse class and create Rust code from it. It follows some kind
        of visitor pattern, the base clase is defined in visitor.py """

    def __init__(self):
        self._main = []
        self._crates = set()
        self._indent = 1

    def output(self, file):
        """ Writes Rust code to the file specified in argument """
        for crate in sorted(self._crates):
            print("use %s;" % crate, file=file)

        print("fn main() {", file=file)
        for line in self._main:
            print("%s%s" % (line.indent * (" " * 4), line.code), file=file)
        print("}", file=file)

    def visit_Program(self, node):
        """ Iterate through all statements in the TinyBasic program and
            generate Rust"""
        for line in node.statements:
            _, statement = line
            self.visit(statement)

    def visit_Let(self, let_node):
        """ Generate Rust from TinyBasic LET, if this is a declaration use let
            mut otherwise just assign. """
        if let_node.declaration:
            code = "let mut %s = %s;" % (let_node.var, let_node.exp)
        else:
            code = "%s = %s;" % (let_node.var, let_node.exp)

        self._main.append(Line(self._indent, code))

    def visit_Print(self, print_node):
        """ Generate Rust from TinyBasic PRINT, by ways of the println! macro
        and the: println!()"{}", arguments), notation. """
        num = len(print_node.exp_list)
        arguments = ",".join(print_node.exp_list)
        code = 'println!("%s", %s);' % ("{}" * num, arguments)
        self._main.append(Line(self._indent, code))

    def visit_Loop(self, loop_node):
        """ Generate Rust code from a TinyBasic (IF/)GOTO loop.

            Turn:
                line-number [statement]
                [...]
                IF exp GOTO line-number
            Into:
                loop {
                    [statement]
                    [...]
                    if !exp {
                        break
                    }
                }
        """
        self._main.append(Line(self._indent, "loop {"))
        self._indent = self._indent + 1
        for (_, statement) in loop_node.statements:
            self.visit(statement)

        if loop_node.conditions is not None:
            conditions = parse.invert_conditions(loop_node.conditions)
            code = "if %s {" % format_condition(conditions)
            self._main.append(Line(self._indent, code))
            self._main.append(Line(self._indent + 1, "break;"))
            self._main.append(Line(self._indent, "}"))

        self._indent = self._indent - 1
        self._main.append(Line(self._indent, "}"))

    def visit_If(self, if_node):
        """ Generate Rust code from TInyBasic IF statement, the grunt work is
            performed by the format_condition() function. """
        code = "if %s {" % format_condition(if_node.conditions)
        self._main.append(Line(self._indent, code))

        self._indent = self._indent + 1
        for _, statement in if_node.then:
            self.visit(statement)
        self._indent = self._indent - 1

        self._main.append(Line(self._indent, "}"))
